Jbeich bsd (#19)
* xdg_shell: Help Clang find declaration after case

src/xdg_shell.c:119:9: error: expected expression
  119 |         wlmtk_window_t *window_ptr = wlmtk_window_create_from_xdg_toplevel(
      |         ^
src/xdg_shell.c:122:16: error: use of undeclared identifier 'window_ptr'
  122 |                window_ptr, wlr_xdg_surface_ptr);
      |                ^

* protocols: Set LINKER_LANGUAGE for Ninja

$ cmake -G Ninja -B /tmp/wlmaker_build
[...]
CMake Error: CMake can not determine linker language for target: protocol_headers
-- Generating done (0.0s)
CMake Generate step failed.  Build files cannot be regenerated correctly.

* libwlclient: Depend on epoll-shim for signalfd on BSDs

ld: error: undefined symbol: signalfd
>>> referenced by client.c
>>>               client.c.o:(wlclient_create) in archive apps/libwlclient/liblibwlclient.a

* submodules: update libbase to pick up BSD fixes

* Adds an INSTALL rule for apps/wlmclock. (#16)

* Removes libdrm and pixman as toplevel dependencies. They're used for wlroots, but not directly.

* Updates to libbase at HEAD, including the PRIVATE mode of ncurses. (#17)

* Surface (#18)

* Minor doxygen fix.

* Moves request_close from surface to content.

* Moves the request_size call from wlmtk_surface_t to wlmtk_content_t.

* Wires up the commit handler of wlr_surface with wlmtk_surface dimensions.

* Moves the create_scene_node and destroy methods into wlmtk_surface_t.

* Moves set_activated to wlmtk_content_t.

* Changes XDG implementation to compose a wlmtk_surface_t, and hides wlmtk_surface_init and wlmtk_surface_fini.